### ISSUE TITLE
Regarding the # of predicates in VG-cur.

### ISSUE THREAD

**Issue by KanghoonYoon** [Maelic/VG_curated#1]
Hi, thank you for sharing your work! I interestingly read your paper at https://arxiv.org/pdf/2305.18668.pdf.

This work highlights a new perspective in the SGG research community, and I have a few questions regarding the paper.

1. In the paper, VG-cur is constructed based on VG150 by filtering the overlapped part-whole predicates in ConceptNet. Then the number of predicates in VG-cur is less than that of VG150, right? If so, the improvement in Table 4 is hard to interpret as it takes for granted that obtaining a higher performance with smaller classes is usual.

2. In Table 4 of the Appendix, the number of images increases 89,168 -> 91,803 as the VG150 is curated. Could you explain the reason?

**Comment by Maelic** [comment]
Hi, first of all thank you for your interest in my work!

1. It is not exactly correct, VG-cur is constructed based on the original VG dataset (not VG150) where one of the differences with the curation process of VG150 is the removal of part-whole relations. Basically, VG-cur contains the top 50 predicates from the original VG that are not related to part-whole rel. Same for the object class distribution. 
The performance in Table 4 should not be taken as a traditional improvement over the baseline because obviously, the distribution of both images and classes are slightly different from VG150 and my version VG150-cur. My goal in those experiments was to demonstrate that a dataset that is supposedly more challenging for baseline models (more triplets + no irrelevant relations) still has better performance and thus highlights the limit of current R@K metrics, as explained in the discussion. In a sense, the comparison is still relevant (to me at least) because the distribution of predicates is roughly similar (88%).

2. This is related to my previous answer, as I am not curating from VG150 but from the original VG instead, I am keeping all images that possess at least one relation annotated and this number happened to be a little bit higher than VG150. The original VG possesses 108,077 images annotated, in the curation process of VG150, authors kept 89,168 and with my new curation process, it is 91,803.

Hope this helps!
